const sidebars = {
  robots: [{type: 'autogenerated', dirName: 'robots'}],
  software: [{type: 'autogenerated', dirName: 'software'}],
  addons: [{type: 'autogenerated', dirName: 'add-ons'}],
};

module.exports = sidebars;
