name: Manual Amplify Preview

on:
  pull_request:
    types: [labeled]

jobs:
  deploy:
    if: contains(github.event.label.name, 'Preview Environment')
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      id-token: write
      pull-requests: write
    steps:
      - name: configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE }}
          output-credentials: true
      - name: deploy PR preview
        uses: clearpathrobotics/amplify-preview-actions@sed-replace-all
        with:
          branch_name: ${{ github.head_ref }}
          amplify_command: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.creds.outputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.creds.outputs.aws-secret-access-key }}
          AmplifyAppId: ${{ secrets.AMPLIFY_APP_ID }}
          AWS_REGION: 'us-east-2'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
